spring:
  application:
    name: content-sale-system
  datasource:
    username: root
    password: WjDh83250239
    url: jdbc:mysql://127.0.0.1:3306/content_sale_system?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      idle-timeout: 300
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/
      suffix: .html

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 文件上传路径配置
upload:
  default: 'D:\file_upload'



